---
- name: Install software on Fedora
  when: ansible_distribution == 'Fedora'
  become: true
  ansible.builtin.dnf:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { name: "conky", state: "present" }

- name: Update software cache for pacman
  when: ansible_distribution == 'ArchLinux'
  become: true
  community.general.pacman:
    update_cache: yes

- name: Install software on ArchLinux
  when: ansible_distribution == 'ArchLinux'
  become: true
  community.general.pacman:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { name: "conky-all", state: "present" }

- name: Update software cache for apt-get
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  become: true
  ansible.builtin.apt:
    update_cache: yes
  changed_when: false

- name: Install software on Ubuntu
  when: ansible_distribution == 'Ubuntu'
  become: true
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { name: "conky", state: "present" }

- name: Install software on Debian
  when: ansible_distribution == 'Debian'
  become: true
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { name: "conky", state: "present" }
    - { name: "conky-all", state: "present" }
    - { name: "lm-sensors", state: "present" }

- name: Install software on openSUSE
  when: ansible_os_family == 'Suse'
  become: true
  community.general.zypper:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { name: "conky", state: "present" }
    - { name: "conky-doc", state: "present" }

- name: Configure Conky
  ansible.builtin.template:
    src: conkyrc.j2
    dest: "~{{ config_owner }}/.conkyrc"
    owner: "{{ config_owner }}"
    group: "{{ config_owner_primary_group }}"
    mode: 0700
