---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Task name
    ansible.builtin.stat:
      path: /home/ansible-test-user/.conkyrc
    register: stat_conkyrc
  - name: Assert that .conkyrc exists
    ansible.builtin.assert:
      that: stat_conkyrc.stat.exists
  - name: Assert that .conkyrc is a regular file
    ansible.builtin.assert:
      that: stat_conkyrc.stat.isreg
  - name: Assert that .conkyrc is owned by user ansible-test-user
    ansible.builtin.assert:
      that: stat_conkyrc.stat.pw_name == 'ansible-test-user'
  - name: Assert that .conkyrc is owned by group ansible-test-user
    ansible.builtin.assert:
      that: stat_conkyrc.stat.gr_name == 'ansible-test-user'
  - name: Assert that .conkyrc has mode 0700
    ansible.builtin.assert:
      that: stat_conkyrc.stat.mode == '0700'
